# Generated by Django 4.1.1 on 2022-10-18 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='category',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(through='portal.Subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
